name: Crosscompile C

on:
  push:
    branches:
      - master
      - main

jobs:
  buildJob:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up GCC to compile C
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
      shell: bash

    - name: Compile C code
      run: gcc -o hello_world Hello_world.c
      working-directory: ${{ github.workspace }}

    - name: Move the new .exe to my repository
      run: mv hello_world ${{ github.workspace }}/hello_world.exe
      working-directory: ${{ github.workspace }}

    - name: Archive the executable
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-executable
        path: ${{ github.workspace }}/hello_world.exe

    - name: install cross compile toolchain
      run: |
        sudo apt install --yes {gcc,binutils}-arm-linux-gnueabihf
      shell: bash
    
    - name: Compile the C program
      run: |
        arm-linux-gnueabihf-gcc -o hello_world_ARMv7.exe Hello_world.c
      shell: bash

#    - name: Move the new .exe to my repository
#      run: mv hello_world_ARMv7 ${{ github.workspace }}/hello_world_ARMv7.exe
#      working-directory: ${{ github.workspace }}

    - name: Archive the executable
      uses: actions/upload-artifact@v2
      with:
        name: hello-world-executable-arm
        path: ${{ github.workspace }}/hello_world_ARMv7.exe


