name: Crosscompile C

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up GCC to compile C
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc
      shell: bash

    - name: Compile C code
      run: gcc -o hello_world Hello_world.c
      working-directory: ${{ github.workspace }}
